services:
  host:
    container_name: unity-docs-host
    build:
      context: .
      dockerfile: src/Host/Dockerfile
      args:
        - BAGET_API_KEY=${BAGET_API_KEY}
    ports:
      - "8893:8893"
    env_file:
      - stack.env
